services:
  - type: web
    name: 1on1-academy-app
    env: node
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production